version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
