version: '3'
services:
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    volumes:
      - /app/node_modules
      - ./node:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    # polling setting for Docker. activate auto reload when file change.
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
